# Generated by Django 5.1.3 on 2024-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('ID_klienta', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('telefon', models.IntegerField()),
                ('login', models.CharField(max_length=10)),
                ('haslo', models.CharField(max_length=30)),
            ],
        ),
    ]
