# Generated by Django 5.1.3 on 2024-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_klient_id_klienta_alter_klient_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
