# Generated by Django 5.1.3 on 2024-12-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_klient_is_active_klient_is_staff_klient_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
