# Generated by Django 5.1.3 on 2024-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_klient_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
