# Generated by Django 5.1.3 on 2024-12-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_klient_haslo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='klient',
            name='haslo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
