# Generated by Django 5.1.3 on 2024-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_klient_groups_remove_klient_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('ID_pracownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('telefon', models.IntegerField()),
                ('login', models.CharField(max_length=10)),
                ('haslo', models.CharField(max_length=30)),
                ('rola', models.CharField(max_length=30)),
            ],
        ),
    ]
