# Generated by Django 5.1.3 on 2024-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
