# Generated by Django 5.1.3 on 2024-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pracownik_email_alter_pracownik_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='is_pracownik',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='is_pracownik',
            field=models.BooleanField(default=True),
        ),
    ]
