# Generated by Django 5.1.3 on 2024-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
