# Generated by Django 5.1.3 on 2024-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_sprzet_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='silnik',
            field=models.CharField(max_length=25),
        ),
    ]
