# Generated by Django 5.1.3 on 2024-11-21 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_sprzet_silnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('ID_klienta', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('telefon', models.IntegerField()),
                ('login', models.CharField(max_length=10)),
                ('haslo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('ID_oferty', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=8000)),
                ('cena', models.FloatField()),
                ('typ_sprzetu', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='sprzet',
            name='id',
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='ID_sprzetu',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sprzet',
            name='ID_oferty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sprzety', to='rental.oferta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('ID_rezerwacji', models.IntegerField(primary_key=True, serialize=False)),
                ('data_poczatku', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('ID_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.klient')),
                ('ID_oferty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.oferta')),
                ('ID_sprzetu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.sprzet')),
            ],
        ),
    ]
