# Generated by Django 5.1.3 on 2024-11-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_klient_oferta_remove_sprzet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('ID_pracownika', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('telefon', models.IntegerField()),
                ('login', models.CharField(max_length=10)),
                ('haslo', models.CharField(max_length=30)),
                ('rola', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('ID_powiadomienia', models.IntegerField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=30)),
                ('tresc', models.CharField(max_length=8000)),
                ('typ', models.CharField(max_length=30)),
                ('ID_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.klient')),
                ('ID_sprzetu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.sprzet')),
                ('ID_pracownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Usterka',
            fields=[
                ('ID_usterki', models.IntegerField(primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=8000)),
                ('status', models.CharField(max_length=20)),
                ('ID_klienta_zglaszajacego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.klient')),
                ('ID_pracownika_naprawiajacego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.pracownik')),
                ('ID_sprzetu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.sprzet')),
            ],
        ),
    ]
