# Generated by Django 5.1.3 on 2024-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_pracownik_alter_rezerwacja_status_powiadomienie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
