# Generated by Django 5.1.3 on 2024-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_oferta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
