# Generated by Django 5.1.3 on 2024-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_remove_oferta_slug_sprzet_id_oferty'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
