# Generated by Django 5.1.3 on 2024-11-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_oferta_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='slug',
        ),
    ]
