# Generated by Django 5.1.3 on 2024-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_remove_oferta_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprzet',
            name='ID_oferty',
        ),
        migrations.AddField(
            model_name='oferta',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
