# Generated by Django 5.1.3 on 2024-11-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_remove_sprzet_id_oferty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='ID_oferty',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='sprzety', to='rental.oferta'),
        ),
    ]
