# Generated by Django 5.1.3 on 2024-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_sprzet_id_oferty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzet',
            name='slug',
            field=models.SlugField(default='marka+"-"+model'),
        ),
    ]
