# Generated by Django 5.1.3 on 2024-11-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_sprzet_slug'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powiadomienie',
            name='ID_klienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient'),
        ),
        migrations.AlterField(
            model_name='usterka',
            name='ID_klienta_zglaszajacego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='ID_klienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient'),
        ),
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
