# Generated by Django 5.1.3 on 2024-12-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_alter_powiadomienie_id_klienta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='ID_rezerwacji',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
