# Generated by Django 5.1.3 on 2024-12-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_alter_sprzet_id_sprzetu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprzet',
            name='status_dostepnosci',
            field=models.CharField(default='dostępny', max_length=15),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='status_zablokowania',
            field=models.CharField(default='zablokowany', max_length=15),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='status_zamkniecia',
            field=models.CharField(default='zamknięty', max_length=15),
        ),
    ]
