# Generated by Django 5.1.3 on 2025-01-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_alter_sprzet_status_dostepnosci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powiadomienie',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
