# Generated by Django 5.1.3 on 2025-01-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0041_powiadomienie_slug'),
        ('users', '0012_klient_is_pracownik_pracownik_is_pracownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usterka',
            name='ID_pracownika_naprawiajacego',
        ),
        migrations.AddField(
            model_name='powiadomienie',
            name='data_wyslania',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='usterka',
            name='data_wyslania',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='ID_klienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.klient'),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='ID_powiadomienia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='powiadomienie',
            name='ID_pracownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pracownik'),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='lokalizacja',
            field=models.CharField(default='Wrocław', max_length=50),
        ),
        migrations.AlterField(
            model_name='sprzet',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='usterka',
            name='ID_usterki',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usterka',
            name='status',
            field=models.CharField(default='w trakcie', max_length=20),
        ),
    ]
